### ISSUE TITLE
current_dir and dir_name conflict

### ISSUE THREAD

**Issue by rosherbal** [saezlab/CARNIVAL#10]
I have realized that some times _runCARNIVAL_ founds solutions, but the pipeline retrieves _"No result to be written"_, without giving any error/warning message. 

I have dug in the code, and I have found that it puts together _current_dir_ and _dir_name_.  _current_dir_  gets the current working directory, and if the _dir_name_ is an absolute path, then you can end up with a nested path that doesn't exist. Due to this conflict, even if there are solutions to be generated, they are never written. 

Be aware that the argument for **_Result_dir_ must NOT be an absolute path**.

**Comment by ptrairatphisan** [comment]
@rosherbal - Thank you very much for your report. Indeed the runCARNIVAL function doesn't support the assignment of a full file path as the name of result folder (e.g. "/home/user/CARNIVAL_Results"). Yet, it still support the assignment of sub-folder (e.g. "output/CARNIVAL_Results"). 

This remark has now been added to the README page on the master branch and also documented in the FAQ section of [CARNIVAL Wiki page](https://github.com/saezlab/CARNIVAL/wiki/FAQs).
