### ISSUE TITLE
Feature Request: Omnipath network from original paper

### ISSUE THREAD

**Issue by josiahbjorgaard** [saezlab/CARNIVAL#100]
Can the omnipath network used in the original paper be provided as part of the repo?

Is it already publically available?

**Comment by gabora** [comment]
@anikaliu @enio23 @ptrairatphisan

**Comment by enio23** [comment]
Hi @josiahbjorgaard ,

On the original paper (https://www.nature.com/articles/s41540-019-0118-z) the Omnipath prior knowledge contained 9306 signed and directed edges connecting 3610 nodes pooled and curated from multiple resources including Signor, Reactome, and Wikipathways.

You can find the omnipath interactions that have been used on the paper release version of CARNIVALhere: https://github.com/saezlab/CARNIVAL/blob/package_paper_version/inst/Ex2_network_SBV_Omnipath.sif.

You can check also on some tutorials on this paper release version of the CARNIVAL package: https://github.com/saezlab/CARNIVAL/tree/package_paper_version.

Cheers,
Enio
