### ISSUE TITLE
R version requirement

### ISSUE THREAD

**Issue by ahmedasadik** [saezlab/CARNIVAL#16]
Dear All,
I noticed that you changed the prerequisit R version in the description file to >=4.0. This stops Carnival installation for R 3.6.3 which was released 6 weeks ago. Could you decrease that to 3.5?
Kind regards,

**Comment by enio23** [comment]
Hello,

Unfortunately, we are preparing CARNIVAL for submission to Bioc and it is a requirement to keep the R version >=4.0 for the release. I would suggest to either update the R version or re-install CARNIVAL locally after downloading and changing the R version on the description.

Cheers,
Enio

**Comment by dereckdemezquita** [comment]
I found that declaring `install_github("saezlab/CARNIVAL@*release")` will install the latest "release" and solve this issue.
