### ISSUE TITLE
Saving CARNIVAL outputs

### ISSUE THREAD

**Issue by LaraFuhrmann** [saezlab/CARNIVAL#17]
Dear all, 
I have some problems saving the outputs of runCARNIVAL() , e.g. weighted_Model.txt, nodesAttribute.txt. etc. These files are just not saved, they appear nowhere on my computer. The only thing being saved when running the function is the DOT-figure. 
I have already tried giving an absolute path and just the directory (as input for 'dir_name'), and with and without DOTfigure saving. 
Do you have an idea what could be the reason?

**Comment by enio23** [comment]
Hello,

you can assign a variable to the runCARNIVAL function: result = runCARNIVAL(). The 'result' function contains a list of results (weighted_Model, nodesAttribute, etc.) which you can save at any directory you wish.

Cheers,
