### ISSUE TITLE
Vignette missing

### ISSUE THREAD

**Issue by kunstner** [saezlab/CARNIVAL#20]
Hi,

it seems the command vignette("CARNIVAL-vignette") leads to a warning:

vignette ‘CARNIVAL-vignette’ not found 

I tried the Bioconductor and the github version but neither versions contain the vignette. Can you fix this?

I'm running CARNIVAL v 1.0.0 on R4.0.1.

Many thanks,
 Axel

**Comment by adugourd** [comment]
Hi, 

Sorry about that.

Please check if you have installed all the packages required to run the vignette. These packages are not automatically installed with the CARNIVAL package (You can find them in the suggested field of the description file or in the vignette itself.)

You can also find here the vignette that was built on bioconductor system : http://bioconductor.org/packages/release/bioc/vignettes/CARNIVAL/inst/doc/CARNIVAL.html


I hope this helps !

Cheers,

Aurelien

**Comment by kunstner** [comment]
Hi @adugourd,

thanks!

Best,
 Axel
