### ISSUE TITLE
node name fixing

### ISSUE THREAD

**Issue by gabora** [saezlab/CARNIVAL#24]
the formatting of node names are done independently for network (`controlNodeIdentifiers`) , inputs (`checkInputObj`) and measurements (`checkMeasObj`).
This should be handled by the same function, if possible, to assure they are done the same way.

**Comment by gabora** [comment]
Worse! 
If a name has an invalid character for CPLEX, for example a dash (-) , then the name is converted in the networkObj  and _then_ it checks which `measurements` are in the `networkObj`. This way, the name appears with a dash in the `measurement`, but already with underscore in the `networkObj` and won't match.

**Comment by enio23** [comment]
Indeed that could bring issues. Symbol conversion now is performed before removing non-present measurements.

**Comment by ivanovaos** [comment]
Redundant code is removed. All called from one place.
