### ISSUE TITLE
reporting removed nodes

### ISSUE THREAD

**Issue by gabora** [saezlab/CARNIVAL#25]
`checkMeasObj`  removes nodes that are not in the networkObj but does not notify the user.

**Comment by enio23** [comment]
Don't think is necessary for reporting them since they can't appear in the solution anyway.

**Comment by gabora** [comment]
yeah, but it is nice to tell people that their prior knowledge is not OK for the current settings. It can be a small mistake in the naming.

**Comment by ivanovaos** [comment]
Done in new dev2_1 branch
