### ISSUE TITLE
Constraint writing takes a very long time

### ISSUE THREAD

**Issue by ivanovaos** [saezlab/CARNIVAL#26]
Review the code part that does it and find optimisations 

Reported by Aurelien

**Comment by enio23** [comment]
Constraint writing is fast except for the ones in write_constraints_6.R and write_constraints_7.R. They are a bit tricky.

**Comment by ivanovaos** [comment]
@enio can you please comment on this opened issue? https://github.com/saezlab/CARNIVAL/issues/15

**Comment by ivanovaos** [comment]
String parsing is not necessary anymore with new internal data representation. Likely, constraints writing is taking much less time and can even be done locally. Requires an extra check/profiling on time.
