### ISSUE TITLE
Confusion about inputs for CARNIVAL

### ISSUE THREAD

**Issue by anu-bioinfo** [saezlab/CARNIVAL#34]
Hello,

I am having some issues understanding the inputs for the CARNIVAL program. 

1). measFile :  I get a matrix (Transcrition Factors as rows and Samples as columns) from DOROTHEA after using run_viper on gene expression matrix and . But the input to CARNIVAL has two rows: the TFs and the values.  Should I take an average for the TF-activity across samples (or Median) to get a two row format ?

2) weightFile:  Similar is the case for the PROGENY output. Can I again take average(or Median) across samples for the pathway scores as well ?

3) inputFile: Can I use the sign fold change of differential gene expression to construct this file ? As in -1 for the down-regulated genes and 1 for upregulated genes ...

Thanks in advance for any help. 

Regards,

Anupam

**Comment by ivanovaos** [comment]
Hi @anu-bioinfo, 

Can you let us know what is your samples - is it bulk RNA-seq data, are those samples replicates? What is the question that you are trying to answer? 

Olga

**Comment by anu-bioinfo** [comment]
Hey @ivanovaos 

Thanks for your quick response. These are bulk RNA-seq  data. These samples are biological replicates. 4 for treatment and 4 for control.
Hence, for both DOROTHEA and PROGENY I get a 8 * n matrix (8 being the total number of samples and n being the number of TFs/Pathways)

Basically, I am comparing the treatment samples with control samples. I wish to find TFs/PPIs/networks which drive the phenotypic difference between the control and the treatment group. 

Thanks for any help.

Regards,

Anupam

**Comment by ivanovaos** [comment]
Hi @anu-bioinfo, 

Are they paired one to one? How many networks you want to get out of CARNIVAL - 4, 8, or 1? 

You can treat this type of analysis with different approaches. If it is 4 networks you want to get, basically the output of CARNIVAL is a network explaining the difference for paired conditions. If it is 8 networks, you get the output explaining each sample, and then you apply network approaches to compare conditions. If it is 1 network, it would be explaining the difference between the averaged signals among 4 treatments/4 controls. 

If it is the first and last case, you need to run DoRoThEA/VIPER on contrasts (not on expression matrices). Then you need to run CARNIVAL as many times as you have inputs (4 or 8, 1). 

Is this helpful? 

Also, there is a new tutorial for all tools [here](https://github.com/saezlab/transcriptutorial)

**Comment by ivanovaos** [comment]
@anu-bioinfo Did it help? Do you need more guidance or we can close the issue?

**Comment by anu-bioinfo** [comment]
Hi @ivanovaos 

Thanks a lot for the tutorial and the message it was really helpful.
