### ISSUE TITLE
error when no solution found ? 

### ISSUE THREAD

**Issue by gabora** [saezlab/CARNIVAL#35]
There is an unhandled error occuring in some cases:
`Error in resList[[1]] : subscript out of bounds
Calls: ... <Anonymous> -> solveCARNIVAL -> solveCARNIVALSingle`

**Comment by ivanovaos** [comment]
Reported by Rosa

**Comment by D-Harouni** [comment]
I am encountering the same problem @gabora @ivanovaos, how can this be resolved?

**Comment by gabora** [comment]
dear @D-Harouni ,

thanks for drawing my attention to this older issue. 
I am working on this now. hopefully we will have a fix next week.

**Comment by gabora** [comment]
this bug is fixed now
