### ISSUE TITLE
Careful with protein identifiers in CARNIVAL

### ISSUE THREAD

**Issue by enio23** [saezlab/CARNIVAL#4]
Hello,

I was running CARNIVAL on a case study and I got an error when cplex was about to solve the ilp problem introduced. The issue was that some of the identifiers had an undesired "-" symbol on it (i.e. genes NKX2-1, NKX3-1, etc.). These symbols are recognised as a minus in the problem formulation and might cause problems. Please be careful with the names of the protein identifiers introduced in the PPI, input or measurement files and not add any mathematical symbol on them.

Cheers,

**Comment by ptrairatphisan** [comment]
This particular issue likely came from the using of prior knowledge network using gene symbols as the identifiers. Two methods to address would be automatically check the node's names for special/mathematics symbols then either 1) return an error to the user to remove them from PKN manually or 2) automatically convert special characters directly upon importing PKN to CARNIVAL. Note that other symbols and configuration e.g. '/' or space would also raise a similar issue for writing the constraints.

Note that we will compile a list of issues and suggestions from the users and developers then open up the Wiki-section of the repository to address these point soon.

**Comment by ptrairatphisan** [comment]
We've now opened a new Wiki-page of the CARNIVAL repository. This particular issue is now listed in the FAQs section where suggestions and potential solutions are provided. Please refer to the following Wiki page: https://github.com/saezlab/CARNIVAL/wiki.
