### ISSUE TITLE
Speed up for carnival

### ISSUE THREAD

**Issue by hmkim** [saezlab/CARNIVAL#43]
Hi,

Is any method of speed up the analysis in carnival?

- Would you suggest the best speed solver? (cbc or cplex)

- multi-processing/threading or anything 

Thank you in advance!

(In my case, there are about 20,000 genes and 171 samples)

**Comment by ivanovaos** [comment]
Hi @hmkim,

We are currently working on speeding up and improvements for CARNIVAL. Some things like speeding up of writing constraints are planned to be implemented until the end of the year. 

Our lab runs CARNIVAL with cplex. It seems to be quite efficient for the majority of the cases if you run it on cluster. We call runCARNIVAL for each sample. 20 000 genes would be "condensed" to the activity of TFs with DoRothEA/Viper or similar, and you can also make your prior knowledge network smaller by selecting e.g. only edges confirmed by lit references or you can also adapt this network to your specific case. Does this help?

**Comment by hmkim** [comment]
@ivanovaos Thank you!

I already checked it (tutorial in your mentioned)

I'll check the cplex on cluster.
