### ISSUE TITLE
revise dependencies

### ISSUE THREAD

**Issue by gabora** [saezlab/CARNIVAL#48]
Hey, 
the following dependencies should be revised: 
Imports:
    doParallel,  --- is it compulsory? 
    readr,  (? not sure if really needed)
    viper, -- (do we need Dorothea for CARNIVAL? or is it only used for the vignette?) 
    AnnotationDbi, -- gene name mapping should be done outside carnival, right? 
    UniProt.ws, -- gene name mapping should be done outside carnival, right?

**Comment by ptrairatphisan** [comment]
doParallel is for cluster computing and not compulsory.
viper is needed for running DoRothEA. We used to provide a script/pipeline for input data processing in the early versions but not anymore in the latest version.
readr, AnnotationDbi and UniProt.ws are for reading files and mapping between UniprotID and gene symbols in the early versions. This pipeline was also removed in the latest version.

-- Summary: I believe all of these dependencies can be removed. Nevertheless, please recheck whether the CARNIVAL pipeline is still stable after disable/remove these dependencies --

@enio23 @anikaliu - any additional thoughts/comments?
