### ISSUE TITLE
CBC multithreading arguments

### ISSUE THREAD

**Issue by ahmedasadik** [saezlab/CARNIVAL#62]
Dear @ivanovaos 
as we discussed in this issue #61, I would suggest that we add two additional options to be sent to the CBC solver command line.
Those would be: ```threads``` and ```randomseed``` , which would help speed up CBC that was built with support for multithreading by adding that option to the config file ```./configure --enable-cbc-parallel```
Many thanks!!
Ahmed

**Comment by gabora** [comment]
thanks @ahmedasadik for your comments. 
the `threads` option is available in the current version.
I just updated the documentation of `runCARNIVAL` documentation

It works nicely with some test networks, with 4 threads the wall time was reduced from 60 to 20 sec.

**Comment by gabora** [comment]
some additional notes:
There is no need to start parallel sessions with the `future` package. 
CARNIVAL uses the interactive interface of `cbc`, so multithreading is handled completely outside of the R environment. 
Just run `runCARNIVAL(..., threads = 4,...)` to use 4 threads.
