### ISSUE TITLE
Wrong column name inside the measurementsDf?

### ISSUE THREAD

**Issue by HenryWotton** [saezlab/CARNIVAL#69]
From[ ```create_lp_formulation.R```](https://github.com/saezlab/CARNIVAL/blob/4bc5fc5e4215e33d6aa7f239094306d76a4cebf7/R/create_lp_formulation.R), function```createGenerals_v2``` :
```
generals <- paste(c(variables$nodesDf$nodesVars,
                      variables$nodesDf$nodesActStateVars,
                      variables$measurementsDf$absDifference), sep="\t")
```
Hello all. Thanks a lot for putting up such fantastic work!

Very sorry for this non-error issue but I wonder if ``` variables$measurementsDf$absDifference``` here should be  ``` variables$measurementsDf$value``` instead? There is no error running the pipeline like this though. 

Having tried this part of the code, I also realised the two values from the ```toy_measurements_ex1.RData``` were not written down at the end of the Generals in the [```toy_lp_file_ex1.lp``` ](https://github.com/saezlab/CARNIVAL/blob/4bc5fc5e4215e33d6aa7f239094306d76a4cebf7/inst/toy_lp_file_ex1.lp)file. Should it be like this? Or is it because those values happen to be 1 so when writing output, it just writes two ```\t```? 
 
Thanks a lot.

**Comment by ivanovaos** [comment]
Hi @HenryWotton,

Thank you, you are very observant! That was indeed a bug that is already fixed in the next bump prepared for submission :)
