### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by fereshtehvosta** [saezlab/CARNIVAL#78]
For my project I read your paper with the title "From expression footprints to causal pathways: contextualizing large signaling networks with CARNIVAL '' and it was really interesting to me, the procedure you applied in different stages was novel and clever. Just some questions remained in my mind and I really appreciate you helping me to answer them: first: what was your request from Omnipath Db to create your PKN network, I downloaded it from Omnipath Db with the following code but I got more interaction than you mentioned in the paper, Can I ask you to send your script for me?
My code:
interactions <-import_omnipath_interactions(resources=c("SignaLink3","PhosphoSite","SIGNOR"))
Secondly: 
As you mentioned in the paper we can use PROGENy tools for pathway activity but I don't understand which format is acceptable? I read your vignette but unfortunately, I didn't find any related data to see what should be this input?
Finally: is it possible for you to send me a real example R script that you run on CARNAVAL? I ran your toy example but for more understanding about its real application, I need a true one.
I hope you help me to answer my questions.
Best Regards

**Comment by gabora** [comment]
Dear @fereshtehvosta 

thanks for writing and sorry for the long waiting time. 

The databases behind Omnipath are in continuous development, therefore It is normal that you found more interactions nowadays. Regarding the code of the mentioned paper, please contact the authors of the paper. 

Sorry that the tutorial provides a very limited example. Please, check our [Transcriptutorial](https://saezlab.github.io/transcriptutorial/) repo, where you can find the whole pipeline from gene expression analysis to network inference with CARNIVAL.

best 
Attila

**Comment by fereshtehvosta** [comment]
Thanks for your response.
I found the Transcriptutorial and I ran it step by step according to your
tutorial but unfortunately I fall into some errors and
03_Pathway_activity_with_Progeny script produced just zero for activity and
I couldn't proceed to the next step.
