### ISSUE TITLE
runCARNIVAL

### ISSUE THREAD

**Issue by fereshtehvosta** [saezlab/CARNIVAL#82]
Hi,
Thanks for developing this great tool, I have one question and your answer is really helpful for me,
Question: I want to run CARNIVAL on a single cell dataset and it contains more than 300 cancer cells, I should run CARNIVAL on each cell separately? because in your transcriptutorial you run it on a for loop. 
**Thanks in advance**

**Comment by gabora** [comment]
Hi @fereshtehvosta, 

We haven't ran CARNIVAL on single cells yet, so I cannot give you reliable information. 
In theory, you can run on single cell level, however the expression data of single cells are usually very noisy. 
Maybe, you could try to identify clusters, then aggregate the cells from the same cluster and then run CARNIVAL on each cluster. 

best,
Attila
