### ISSUE TITLE
Error in file(file, "rt"): cannot open the connection

### ISSUE THREAD

**Issue by whiteorchid** [saezlab/CARNIVAL#88]
Dear respectful developers, 

May I apply for your guidance at your convenient time about runCARNIVAL step?

When using the latest version cplex and VARNIVAL and R4.1.3, in the runCARNIVAL step, it saved the lp file, and then shows **Error in file(file, "rt"): cannot open the connection**, and cplex seems not  generate the results file in the working directory as expected. 

Thanks a lot! Much Appreicate!

**Comment by whiteorchid** [comment]
The V1.3 version of VARNIVAL does not have this issuel. Thanks a lot!

**Comment by gabora** [comment]
Hi, 
this can happen if for some reason the cplex is interrupted (e.g. the operating system kills the process because memory limit reached). 
please follow saezlab/cosmosR#17
