### ISSUE TITLE
progenyMembers.RData

### ISSUE THREAD

**Issue by anikaliu** [saezlab/CARNIVAL#89]
Hey Saezlab:) 

I found an error in progenyMembers.RData: The p53 pathway is mapped to "P53" in the file, but in Omnipath it is called "TP53".

As consequence, I've been getting this warning:
`These nodes are not in prior knowledge network and will be ignored: P53`

This might have been simply my mistake back in the days, but if it is due to updates in gene name conventions this might be something to look out for more generally? 

All the best,
Anika

**Comment by gabora** [comment]
Hello!😁
I think I removed that file from the latest Carnival because I found no reference to that file. So how did you find it?😂

I think the naming difference comes from the fact that progeny uses protein names (P53) and Omnipath uses either uniprotId or gene names (TP53).
S

**Comment by anikaliu** [comment]
Haha, it's still in the current BioConductor version:D
Loaded it through:
`load(file = system.file("progenyMembers.RData",package="CARNIVAL"))`

What do you mean by updating the text instead of changing the name? It needs to map the progeny pathway to the protein node, so gene name, right? 

Also do you mean, you removed it because none of the functions are using it? It's needed to get node weights from progeny pathway activity, so "pre-processing". Would be good to have this available in some form, but also saw it in the transcriptutorial repo.
