### ISSUE TITLE
Description about the output

### ISSUE THREAD

**Issue by harimchun** [saezlab/CARNIVAL#90]
Hi, Saez lab,

I am interested in using CARNIVAL with my TF activity data and thank you for making this helpful tool.

However, I am struggling with using the CARNIVAL. 

First, I am curious about the output.
From the tutorial, there're NodeTypes with "P" and "M" and I can't understand what these mean. Are there any documents for a clear description of the results? I could only get the information about what weighetdSIF, nodesAttributes., etc are.

Second, I am wondering about the method for the visualization.
From the transcript tutorial, there's a function called "carnival_visNet". However, this function is not compatible with the results generated by the latest runCARNIVAL() or runInverseCarnival() function. Also, I want to know how to visualize the network using Cytoscape. 

Thanks in advance!

Best,
Harim

**Comment by adugourd** [comment]
Hi Harim,

Thanks for your interest in our tool :)

P means "Perturbed", these are nodes that were given in the input paramater of the carnvial function.

M means "Measured", these are the nodes that were given as measurements parameter to the carnival function.

The best way to import the result in cytoscape is simply to export the weightedSIF and nodesAttributes table as CSV files (see code under)
```
SIF <- as.data.frame(carni_res$weightedSIF)
ATT <- as.data.frame(carni_res$nodesAttributes)

write_csv(SIF, file = "results/SIF.csv")
write_csv(ATT, file = "results/ATT.csv")
```
Then you can import those files as SIF network and Attributes in cytoscape (you have buttons for that in the toolbar of cytoscape.

You can then adjust the style to your liking :)

Cheers,

Aurelien

**Comment by harimchun** [comment]
Thank you for the reply, Aurelien!

It really helps a lot!

I also think using Cytoscape for the visualization is the best way.
Then how about using the "carnival_visNet" from the transcript tutorial? I think it utilizes visNetwork and is quite simple to visualize the network.

Thanks!

Best,
Harim

**Comment by adugourd** [comment]
Hi Harim,

It can be use with some tinkering of the code, but for simplicity, it's probably better to stick with cytoscape for now :)

Cheers,

Aurelien

**Comment by harimchun** [comment]
Thanks!

I'll try Cytoscape.
