### ISSUE TITLE
error running Carnival with cbc solver

### ISSUE THREAD

**Issue by elcamb** [saezlab/CARNIVAL#91]
I'm using the runInverseCarnival function on my RNAseq data using the output of dorothea as measurements (217 TFs, tried also with 50), the output of progeny as weights and the omnipath interactome (sif, processed as suggested in the tutorial).
I've set the Carnival options as follows:

carnivalOptions <- defaultCbcSolveCarnivalOptions()
carnivalOptions$solverPath <- "cbc/cbc"
carnivalOptions$threads <- 15
carnivalOptions$timelimit <- 3600*0.5
carnivalOptions$keepLPFiles <- FALSE
checkOptionsValidity(solver = "cbc")

dir.create("CBC_Carnival", showWarnings = FALSE)
carnivalOptions$outputFolder <- "CBC_Carnival"

and am calling the function like so:
resultCarnival <- runInverseCarnival(
    measurements = measurements,
    priorKnowledgeNetwork = sif,
    weights = weights,
    carnivalOptions = carnivalOptions
  )

I'm getting the following error, and I'm not sure if it's an issue with something I'm doing or with accessing cbc

--- Start of the CARNIVAL pipeline ---
10:27:35 11.07.2022 Carnival flavour: inverse
Perturbations are not provided, all parents nodes are added as potential perturbations.
Warning in checkMeasurements(measurements, nodesPriorKnowledgeNetwork) :
  These measurement nodes are not in prior knowledge network and will be ignored: TFAP2C | ZNF263 | PRDM14 | ZNF384 | ZBTB7A | PBX2 | ZFX | CTCFL | SNAI2 | ZKSCAN1 | FOXP1
Warning in checkWeights(weights, nodesPriorKnowledgeNetwork) :
  These nodes are not in prior knowledge network and will be ignored: P53
10:27:35 11.07.2022 Generating variables for lp problem
10:27:35 11.07.2022 Done: generating variables for lp problem
Saving preprocessed data.
Done: saving parsed data: CBC_Carnival//parsedData_t10_27_35d11_07_2022n93.RData
10:27:35 11.07.2022 Generating formulation for LP problem
10:27:47 11.07.2022 Done: generating formulation for LP problem.
Saving LP file
Done: Saving LP file: CBC_Carnival//lpFile_t10_27_35d11_07_2022n93.lp
10:28:01 11.07.2022 Solving LP problem
sh: cbc/cbc: Permission denied
Warning in file(file, "rt") :
  cannot open file 'CBC_Carnival//result_t10_27_35d11_07_2022n93.csv': No such file or directory
Error in file(file, "rt") : cannot open the connection

Can you please help?

Thanks,

Emanuele

**Comment by gabora** [comment]
Dear Emanuele, 

thanks for contacting. Based on your error report, R could not launch the CBC solver:
note the 4th line from the bottom: 
> sh: cbc/cbc: Permission denied

if CBC was launched, then no results were generated, which led to the final error.

honestly, I haven't seen this issue before, but it might be easily solved by changing the file permissions, e.g. following this link: https://www.educative.io/answers/how-to-resolve-the-permission-denied-error-in-linux

best,
Attila

**Comment by fritz616** [comment]
Hi, 

I am having the same issue although it says nothing about CBC solver. Maybe no results were generated? If that's the case then how can I check that and fix it?

Jakub

--- Start of the CARNIVAL pipeline ---
23:42:37 16.07.2023 Carnival flavour: vanilla
23:42:37 16.07.2023 Generating variables for lp problem
23:42:37 16.07.2023 Done: generating variables for lp problem
Saving preprocessed data.
Done: saving parsed data: ToyExample1/parsedData_t23_42_37d16_07_2023n56.RData
23:42:37 16.07.2023 Generating formulation for LP problem
23:42:37 16.07.2023 Done: generating formulation for LP problem.
Saving LP file
Done: Saving LP file: ToyExample1/lpFile_t23_42_37d16_07_2023n56.lp
23:42:37 16.07.2023 Solving LP problem
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'ToyExample1/result_t23_42_37d16_07_2023n56.csv': No such file or directory
